FROM joshbetz/wordpress

WORKDIR /usr/src/wordpress

ENV WPCLI_VERSION %%WPCLI_VERSION%%
ENV WPCLI_SHA512 %%WPCLI_SHA512%%

# Install wp-cli
RUN set -ex; \
	curl -o /usr/local/bin/wp -SL https://github.com/wp-cli/wp-cli/releases/download/v${WPCLI_VERSION}/wp-cli-${WPCLI_VERSION}.phar; \
	echo "$WPCLI_SHA512 /usr/local/bin/wp" | sha512sum -c -; \
	chmod +x /usr/local/bin/wp; \
	wp --allow-root --version

USER www-data
CMD ["wp", "shell"]
