#!/bin/bash

# Required first parameter: GitHub repo in the form owner/repo
plugin=$1
plugin=(${plugin//\// })

# Optional second parameter: directory (defaults to mu-plugins)
directory=${2:-mu-plugins}

# Optional third parameter: tag or sha to checkout (defaults to main)
ref=${3:-main}

set -ex

case "$directory" in
	'mu-plugins')
		DIRECTORY=/var/www/wp-content/mu-plugins
		;;
	'plugins')
		DIRECTORY=/var/www/wp-content/plugins
		;;
	'themes')
		DIRECTORY=/var/www/wp-content/themes
		;;
esac;

mkdir -p "$DIRECTORY"

curl -L -o "${plugin[1]}.tar.gz" \
	"https://github.com/${plugin[0]}/${plugin[1]}/tarball/${ref}/"

plugin="${plugin[1]}"

mkdir -p "/var/www/wp-content/${directory}/${plugin}"
tar -xzf "${plugin}.tar.gz" --strip-components 1 -C "${DIRECTORY}/${plugin}"

# Symlink main plugin file into mu-plugins directory
if [[ "$directory" == "mu-plugins" ]]; then
	cd /var/www/wp-content/mu-plugins

	[[ -f "/var/www/wp-content/mu-plugins/${plugin}/${plugin}.php" ]] &&
		ln -s "${plugin}/${plugin}.php" .

	cd -
fi 

rm "${plugin}.tar.gz"
