#!/bin/bash

# Required first parameter: GitHub repo in the form owner/repo
plugin=$1
plugin=(${plugin//\// })

# Required second parameter: dropin file name
dropin=$2

# Optional third parameter: tag or sha to checkout (defaults to main)
ref=${3:-main}

set -ex

DROPIN_PATH=/var/www/wp-content

mkdir -p "$DROPIN_PATH"

curl -L -o "${plugin[1]}.tar.gz" \
	"https://github.com/${plugin[0]}/${plugin[1]}/tarball/${ref}/"

plugin="${plugin[1]}"

mkdir -p "/var/www/wp-content/${plugin}"
tar -xzf "${plugin}.tar.gz" --strip-components 1 -C "${DROPIN_PATH}/${plugin}"

mv "${DROPIN_PATH}/${plugin}/${dropin}" "$DROPIN_PATH"

rm "${plugin}.tar.gz"
rm -rf "${plugin}"
