#!/bin/bash

plugin=$1
dropin=$2

set -exo pipefail

mkdir -p /var/www/wp-content/mu-plugins

version=$(curl -s "https://api.wordpress.org/plugins/info/1.0/${plugin}.json" | jq -r .version)
curl "https://downloads.wordpress.org/plugin/${plugin}.${version}.zip" \
	--output "${plugin}.zip" \
|| curl "https://downloads.wordpress.org/plugin/${plugin}.zip" \
	--output "${plugin}.zip"

unzip "${plugin}.zip"

mv "./${plugin}/${dropin}" /var/www/wp-content/

rm "${plugin}.zip"
rm -rf "${plugin}"
