#!/bin/bash

plugin=$1
dropin=$2

DROPIN_PATH=/var/www/wp-content/

set -exo pipefail

mkdir -p "$DROPIN_PATH"

version=$(curl -s "https://api.wordpress.org/plugins/info/1.0/${plugin}.json" | jq -r .version)
curl "https://downloads.wordpress.org/plugin/${plugin}.${version}.zip" \
	--output "${plugin}.zip" \
|| curl "https://downloads.wordpress.org/plugin/${plugin}.zip" \
	--output "${plugin}.zip"

unzip "${plugin}.zip"

mv "./${plugin}/${dropin}" "$DROPIN_PATH"

rm "${plugin}.zip"
rm -rf "${plugin}"
