#!/bin/bash

plugin=$1
plugin=(${plugin//\// })
dropin=$2

set -ex

DROPIN_PATH=/var/www/wp-content

mkdir -p "$DROPIN_PATH"

curl -L -o "${plugin[1]}.tar.gz" \
	"http://github.com/${plugin[0]}/${plugin[1]}/tarball/master/"

plugin="${plugin[1]}"

mkdir -p "/var/www/wp-content/${plugin}"
tar -xzf "${plugin}.tar.gz" --strip-components 1 -C "${DROPIN_PATH}/${plugin}"

mv "${DROPIN_PATH}/${plugin}/${dropin}" "$DROPIN_PATH"

rm "${plugin}.tar.gz"
rm -rf "${plugin}"
