#!/bin/bash

repo=$1
plugin=$2
directory=${3:-mu-plugins}

set -exo pipefail

case "$directory" in
	'mu-plugins')
		DIRECTORY=/var/www/wp-content/mu-plugins
		;;
	'plugins')
		DIRECTORY=/var/www/wp-content/plugins
		;;
	'themes')
		DIRECTORY=/var/www/wp-content/themes
		;;
esac;

case "$repo" in
	'plugin')
		version=$(curl -s "https://api.wordpress.org/plugins/info/1.0/${plugin}.json" | jq -r .version)
		;;

	'theme')
		version=$(curl -s "http://api.wordpress.org/themes/info/1.2/?action=theme_information&request%5Bslug%5D=${plugin}" | jq -r .version)
		;;

	*)
		echo "Invalid operation ${repo}"
		exit 1
		;;
esac;

mkdir -p "$DIRECTORY"

# download zip
# try latest version first, but fallback to trunk
curl -f "https://downloads.wordpress.org/${repo}/${plugin}.${version}.zip" \
	--output "${plugin}.zip" \
|| curl -f "https://downloads.wordpress.org/${repo}/${plugin}.zip" \
	--output "${plugin}.zip"

unzip "${plugin}.zip" -d "$DIRECTORY"

# Symlink main plugin file into mu-plugins directory
if [[ "$directory" == "mu-plugins" ]]; then
	cd /var/www/wp-content/mu-plugins

	[[ -f "/var/www/wp-content/mu-plugins/${plugin}/${plugin}.php" ]] &&
		ln -s "${plugin}/${plugin}.php" .

	cd -
fi 

rm "${plugin}.zip"
