name: Version Bump
on:
  push:
  schedule:
    - cron: "0 0/6 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Build
        run: |
          ./build.sh
          ./ci.sh
