name: build-and-deploy

on:
  schedule:
    - cron:  '30 * * * *'
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: actions/checkout@v3

      - run: |
          git config user.email "j+bot@joshbetz.com"
          git config user.name "Josh Bot"
          ./ci.sh
